<tr width="100%" style="border: none;">
 <td style="border: none;" width="120px">
    <img align="left" src="https://i.imgur.com/zC3NxsV.png" width="130"/> 
  </td>
  <td style="border: none;" width="80%">
    <h1><a>Uma Breve Introdução ao Julia</a></h1>
    <td>
</tr>
<tr width="100%" style="border: none; text-align: left">
    <td colspan="2" style="border: none; text-align: left">
        <body> Leandro Bataglia, Pedro Machado, Gabriel Marinho, <br> Filipe Braida, Juliana Zamith, Leandro Alvim e Raul Ferreira </body>
    </td>
    </tr>

## Características da Linguagem

`Julia` é uma linguagem _open source_ criada para ter **a velocidade do C**, **o dinamismo do Ruby**, **a homoiconicidade** (capacidade da linguagem se referir a si mesma) **do Lisp** com uma **notação matemática como a do Matlab**. Além disso, foi criada, também, para poder ser **usada em programação geral como o Python**, **fácil para estatísticas como o R**, **natual em processamento de string como o Pearl**, **poderosa para álgebra linear como o Matlab**, **boa para juntar programas como o shell**, além de ser **fácil par aprender**. Uma linguagem de programação criada para ser **interativa e compilada**.

O design da linguagem teve como principio a alta performance e ela gera código nativo eficiente para múltiplas plataformas através do LLVM. 
Para começar, a linguagem Julia tem como referencia várias sintaxes de linguagens de programação modernas, como por exemplo o Matlab, Python, Ruby, Perl, Lisp, Go e outras. Algumas características gerais: a **não necessidade do uso do caractere ';'**, as **estruturas dos blocos como as do Matlab, com a _keyword_ `end` usada para definir o fim do bloco** e a **declaração dinâmica**.

Mais sobre o porquê da criação da linguagem `Julia` pode ser encontrado acessando o link [Why we created Julia]

[why we created julia]: https://julialang.org/blog/2012/02/why-we-created-julia/

## Tipos

`Julia` possui uma ampla variedade de tipos, com uma grande possibilidade de tipos numéricos por conta da definição do tamanho do número de bits e do sinal. Alguns dos tipos mais comuns em `Julia` são: `Float16`, `Float32` e `Float64` para tipos primitivos de **ponto flutuante**; `Bool` para **booleanos**; `Char` para **caracteres**; `Int8`, `UInt8`, `Int16`, `UInt16`, `Int32`, `UInt32`, `Int64`, `UInt64`, `Int128` e `UInt128` para **inteiros**. Podemos ver, nos tipos inteiros, que temos a **definição do tamanho dos bytes** e o **sinal**, representado pela adição da letra U antes do tipo.

Além disso, `Julia` também conta com estruturas básicas como **tuplas**, **strings**, **dicionários** e **arrays** que serão vistos mais pra frente.

## Declaração de variáveis

Julia é uma linguagem que oferece o melhor dos dois mundos (estático e dinâmico) no que tange a tipagem dos dados. Ele possui um sistema de tipagem dinâmica, e consegue ganhar vantagens que derivam da tipagem estática inferindo ou definindo o tipo específico das variáveis.

In [95]:
b = 3
a = b + 1
typeof(a)

Int64

In [96]:
a = b + 1.0
typeof(a)

Float64

In [97]:
x = 20
typeof(x)

Int64

In [98]:
x = 1.5
typeof(x)

Float64

In [99]:
x = "10"
typeof(x)

String

Nos casos acima, podem ser atribuídos diferentes tipos de valores a variável `x`. Isto faz com que o programa não tenha conhecimento dos tipos da variável até a hora da execução. Isso dá ao programador uma maior flexibilidade na hora de escrever o código, mas, por outro lado, faz com que tenhamos que ter mais cuidado ao escrevê-lo.

Por outro lado, `Julia` também permite a definição de tipos para as variáveis. Para fazê-lo, é necessário o uso do operador `::` que atribui o tipo à variável. Porém, não é possível a definição de tipos no escopo global.

In [100]:
x::Int64 = 1

LoadError: syntax: type declarations on global variables are not yet supported

In [101]:
let
    y::Int64 = 1
end

1

In [102]:
let
    y::Int64 = 1
    y = "casa"
end

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

### Situações com a definição de tipos

A definição de tipos, atualmente, é suportada em contextos de **funções**. Neles, podemos definir os tipos das variáveis **de dentro da função**, **de seus parâmetros** e de seu **retorno**. Além disso, `Julia` também permite a definição de tipos de variáveis dentro do escopo de uma **struct**.

In [ ]:
# Definição do tipo da variável X no escopo da função foo1()
function foo1()
   x::Int64 = 100
   x
end

# Definição do tipo da variável X no escopo da função e de seu retorno
function foo2()::Int64
   x::Int64 = 100
   x
end

# Definição do tipo da do parâmetro X da função foo3()
function foo3(x::Int64)
   x
end

# Definição do tipo da variável number no escopo da struct.
struct teste
    number::Int64
end

## Operadores

Julia conta com operadores **lógicos**, **aritméticos** e **relacionais**.

### Operadores lógicos
Os operadores lógicos são curto-circuitados. Isso significa que não precisamos fazer TODAS as relações caso uma delas já nos diz o resultado.

In [103]:
# Usando o operador AND, representado por &&
false && true

false

In [104]:
# Usando o operador OR, representado por ||
true || false

true

In [105]:
# Usando o operador NOT, representado por !
!true

false

In [106]:
true || println("Não é executado")

true

In [107]:
false || println("É executado")

É executado


### Operadores aritméticos

In [108]:
a = 19
b = 3

a + b

22

In [109]:
a - b

16

In [110]:
a * b

57

In [111]:
a / b

6.333333333333333

In [112]:
a ÷ b

6

In [113]:
a \ b

0.15789473684210525

In [114]:
a ^ b

6859

In [115]:
a % b

1

In [116]:
α, β = 21, 2

🎒🚀 = 2α 

42

In [117]:
🎒🚀

42

### Operadores relacionais

Sobre os operadores relacionais é importante destacar que eles geram **valores booleanos**. Isto é, caso atribuamos uma operação relacional a uma variável, esta pode receber os valores `true` ou `false`.

In [118]:
a = 19
b = 9

a > b

true

In [119]:
a < b

false

In [120]:
a == b

false

In [121]:
a != b

true

In [122]:
a >= b

true

In [124]:
typeof(a <= b)

Bool

## Funções

Nos exemplos acima, mostramos a declaração de tipos em uma função. Essa função, assim como as funções no geral em Julia e em outras linguagens, são operações agrupadas em um escopo que serão executadas toda vez que a função for chamada. Desta forma, podemos evitar repetição de código, deixando-o mais limpo e legível.
As funções em Julia são _first-class citizens_. Além disso, existe um suporte para função anônima e, para ter a sintaxe próxima da matemática, existem diversas forma para a declaração da função.

Para definir uma função, começamos com a *keyword* `function` seguida pelo nome da função e, entre parênteses os parâmetros. Seu corpo, assim como as estruturas condicionais ou de repetição (faladas mais adiante), possuem o corpo indentado com um *tab*, o que não é necessário, e terminam com a *keyword* `end`.

In [ ]:
function example1(x)
    return x + 1
end

In [125]:
example2(x) = x + 1
example2(2)

3

In [126]:
example3 = x -> x + 1 #Exemplo de função anônima
example3(2)

3

In [ ]:
function example4(x) #o retorno é opcional e será retornado o último valor executado
    x + 1
end

In [ ]:
function example5() #É possível ter retorno void em Julia
    return nothing
end

In [ ]:
function example6()
    nothing
end

#### Exemplo

Caso queiramos implementar uma função que recebe dois valores e nos retorna a soma desses valores, fazemos

In [127]:
function sum(a, b)
    return a + b
end

sum (generic function with 1 method)

A função acima nos retorna a soma de dois números. Porém, a função não define o tipo dos parâmetros e do retorno da função. Assim, em tese, é possível passar uma `String` para a função, o que resultaria em um erro. Se quisermos definir o tipo dos parâmetros e do retorno da função, vamos utilizar o conceito visto anteriormente sobre tipagem. Faremos:

In [128]:
function sum(a::Int8, b::Int8)::Int8
    return a + b
end

sum (generic function with 2 methods)

Desta forma fazemos com que a função obrigue os parâmetros recebidos a serem do tipo `Int8` e o retorno a ser, também, um `Int8`.

Outra maneira de se criar uma função é a partir desta forma mais curta. ([Manual de funções do Julia])

[Manual de funções do Julia]: https://docs.julialang.org/en/v1/manual/functions/

In [ ]:
sum(a::Int8, b::Int8)::Int8 = a + b

## Estruturas condicionais

Quando queremos dar um rumo à tarefa de acordo com um condição, utilizamos as chamadas **estruturas condicionais**. Estas são estruturas que utilizam condições para a realização de alguma tarefa. Assim, caso tenhamos dois ou mais fluxos de execução, podemos usar essas estruturas para separar e definir cada um desses possíveis caminhos de acordo com o resultado desta condição. Este resultado é de tipo `Bool`, que pode ser verdadeiro, com o valor lógico `true`, ou falso, com o valor lógico `false`.

In [129]:
x = 3
y = 5

if x > y
    print("X é maior.")
end

Acima temos uma estrutura condicional simples, onde apenas o caso verdadeiro é executado. No entanto, caso queiramos que alguma tarefa seja executada para o caso
de essa expressão retornar o valor `false`, utilizamos a *keyword* `else`, da seguinte forma:

In [130]:
x = 3
y = 5

if x > y
    print("X é maior")
else
    print("X é menor.")
end

X é menor.

Desta forma, caso o valor contido em X NÃO seja maior do que o valor contido em Y, o programa irá mostrar uma outra mensagem, informando que X é menor. 
Porém, existe uma outra condição para o caso de a primeira ser falsa: o caso em que x é **igual** a y. Se deixarmos o programa do jeito que está acima e
essa condição for satisfeita, teremos uma saída errada. Podemos, para resolver esse problema, adicionar um outro `if` para que ele teste se o valor contido
em x é igual ao valor contido em Y. Entretanto, usar apenas `if`s faz com que nosso programa perca desempenho, visto que ele terá de testar **todas** as condições
mesmo que a primeira já tenha dado o valor `true`.
Assim, conheceremos uma nova keyword: a `elseif`.

In [131]:
x = 3
y = 5

if x > y
    print("X é maior do que Y")
elseif x == y
    print("X é igual a Y")
else
    print("X é menor do que Y")
end

X é menor do que Y

O `elseif` faz a mesma coisa que um `if` dentro um `else`. Ou seja, caso a expressão do `if` retorne um valor `false`, o `elseif` é acionado e faz uma outra condição.
No exemplo acima, a condição é verificar se o valor de X é igual ao valor de Y.

### Operador ternário

O operador ternário funciona como um if-else mais simplificado. Para fazê-lo, basta digitar `a ? B : c`, onde `a` é a condição, `b` é a operação caso a condição seja 
verdadeira e `c` é a operação caso a condição seja falsa.
Por exemplo, suponhamos que queremos *printar* uma mensagem na tela dependendo do valor de um número, armazenado em `x`: caso este valor seja maior do que 3.14, *printamos*
"Maior que PI" e, caso contrário, "Menor ou igual a PI".

In [132]:
x = 3.18
print(x > 3.14 ? "Maior que PI" : "Menor ou igual a PI")

Maior que PI

Desta forma, temos um print mais simplificado. Se usássemos, ao invés disso, o if-else convencional, teríamos 5 linhas de código.

## Vetores

Vetores (ou *arrays* unidimensionais) são estruturas que armazenam dados. Isto é, caso queiramos armazenar o nome de todos os alunos de uma sala, por exemplo, podemos armazená-los em um vetor. Em Julia, vetores são inicializados utilizando `[1, 2, 3]`, quase como no Matlab.

In [133]:
array = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [ ]:
🚀 = () -> nothing # Uma função declarada em uma variável

In [134]:
a = [🚀, "Mochila", 42]

3-element Array{Any,1}:
   #5 (generic function with 1 method)
   "Mochila"
 42

O acesso a um elemento array é feito com `[]`, com seu índice iniciando em 1, diferentemente do C que inicia em 0. Assim, caso queiramos retornar a primeira posição do array, devemos o fazer com `array[1]`.

In [135]:
array = [10, 20, 30, 40, 50]

5-element Array{Int64,1}:
 10
 20
 30
 40
 50

In [136]:
array[1] # printa o valor 10

10

In [137]:
array[0] # printa um erro de acesso às posições do vetor, chamado de BoundsError

LoadError: BoundsError: attempt to access 5-element Array{Int64,1} at index [0]

### Inicialização com `zeros()` ou `ones()`

Além de inicializar o vetor da forma que vimos acima, o `Julia` nos permite criar arrays com todos os elementos zerados utilizando a função `zeros()` ou a função `ones()`, que pode receber parâmetros indicando o tipo e a dimensão do nosso array. Caso o tipo não seja definido, como vemos nos dois primeiros exemplos abaixo, o array é criado com o tipo `Float64`. Já nos dois exemplos mais abaixo, temos a definição do tipo do array para `Int`.

In [138]:
zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [139]:
ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [141]:
zeros(Int8, 2)

2-element Array{Int8,1}:
 0
 0

In [142]:
ones(Int, 2)

2-element Array{Int64,1}:
 1
 1

### [1, 2, 3] vs [1 2 3]

Criar um array utilizando vírgulas ou não para separar os elementos pode ter uma diferença maior do que parece. Por exemplo, criar um array utilizando o código `a = [1, 2, 3]`, como vimos anteriormente, cria um array de 3 elementos. Porém, quando fazemos o mesmo sem utilizar as vírgulas, temos uma **matriz 1x3 (array de duas dimensões)** e não um **array de 3 elementos**.

In [143]:
array = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [144]:
matrix = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

## Matrizes

As matrizes são formalmente definidas como uma sequência de valores distribuídos múltiplas dimensões, e são uma das estruturas mais utilizadas para o agrupamento de valores com uma mesma finalidade.

As formas de inicialização desta estrutura são simples. Como podemos ver abaixo, ela funciona, basicamente, como a criação do array unidimensional. Porém, ao invés de usarmos vírgula para separar os elementos de uma linha, utilizamos espaço e, além disso, separamos as linhas umas das outras, como no exemplo:

In [145]:
matrix = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [158]:
matrix[1, 2]  # é possível referir-se a uma estrutura multidimensional de forma unidimensional

2

### Inicialização com `zeros()` ou `ones()`

Assim como podemos inicializar um array unidimensional utilizando as funções `zeros()` e `ones()`, podemos o fazer para criar matrizes, ou arrays multi-dimensionais. Basta adicionar um outro parâmetro, indicando mais uma dimensão. Abaixo, criamos duas matrizes 2x3 utilizando esses métodos.

In [149]:
zeros(Int, 2, 3)

2×3 Array{Int64,2}:
 0  0  0
 0  0  0

In [153]:
ones(Int, 2, 3)

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

## Estruturas de repetição

Os laços de repetição são estruturas que têm como objetivo a execução repetida de uma determinada tarefa ao decorrer do código. Por exemplo, caso queiramos percorrer um vetor, podemos utilizar uma estrutura de repetição para iterar sobre os elementos armazenados na estrutura. O uso dessas estruturas de repetição facilitam nosso trabalho na manipulação de arrays.
Em Julia, estas estruturas têm como base alguma expressão condicional ou algum elemento iterável que dita até quando a determinada tarefa irá ser executada. A linguagem nos proporciona três tipos de estruturas de repetição: o `for`, o `foreach` e o `while`.

In [154]:
names = ["Leandro", "Pedro", "Gabriel", "Braida", "Juliana", "Alvim", "Raul", "Freixo"]

println("----LAÇO FOR----")
for i = 1:length(names)
    println(names[i])
end

----LAÇO FOR----
Leandro
Pedro
Gabriel
Braida
Juliana
Alvim
Raul
Freixo


In [155]:
println("\n----LAÇO FOREACH----")
for name in names
    println(name)
end


----LAÇO FOREACH----
Leandro
Pedro
Gabriel
Braida
Juliana
Alvim
Raul
Freixo


In [156]:
println("\n----LAÇO WHILE----")
i = 1
while i <= length(names)
    println(names[i])
    i += 1
end


----LAÇO WHILE----
Leandro
Pedro
Gabriel
Braida
Juliana
Alvim
Raul
Freixo


### Operador *dois-pontos* ou ':'

Quando lidamos com array, queremos poder ter a capacidade de selecionar **todos** os valores em uma linha ou coluna, por exemplo. Para isso, ao invés de fazermos um loop explicitamente, podemos fazer o uso do **operador *dois-pontos***, que serve para nos dar **todas** as instâncias em uma linha ou coluna. Por exemplo, se quisermos todos os elementos de **todas as linhas e da coluna 3**, podemos simplesmente fazer `matrix[:, 3]`. Além disso, o operador *colon* pode nos dar intervalos, bastando adicionar o **índice inicial**, o **intervalo** (caso seja um intervalo com o *step* personalizado) e o **índice final** do intervalo. Caso o operador seja usado para gerar um intervalo apenas com o índice inicial, devemos utilizar a *keyword* `end` para definir o fim do array.
Vejamos os exemplos a seguir.

#### Retornando as instâncias de todas as linhas/colunas

In [157]:
matrix = [1 2 3 4 5 6; 7 8 9 10 11 12; 13 14 15 16 17 18; 19 20 21 22 23 24; 25 26 27 28 29 30; 31 32 33 34 35 36]

6×6 Array{Int64,2}:
  1   2   3   4   5   6
  7   8   9  10  11  12
 13  14  15  16  17  18
 19  20  21  22  23  24
 25  26  27  28  29  30
 31  32  33  34  35  36

In [159]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[:, 2] # linhas na coluna 2

6-element Array{Int64,1}:
  2
  8
 14
 20
 26
 32

In [160]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[1, :] # colunas da primeira linha

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

#### Retornando as instâncias de todas as linhas/colunas iniciando em um valor específico

In [ ]:
# matriz
#  1  2  3  4  5  6
#  7  8  9 10 11 12
# 13 14 15 16 17 18
# 19 20 21 22 23 24
# 25 26 27 28 29 30
# 31 32 33 34 35 36

In [161]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[2:end, 4] # todas as linhas, a partir da segunda, na coluna 4

5-element Array{Int64,1}:
 10
 16
 22
 28
 34

In [162]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[5, 4:end] # todas as colunas, a partir da quarta, na linha 5

3-element Array{Int64,1}:
 28
 29
 30

#### Retornando as instâncias em um intervalo personalizado

In [ ]:
# matriz
#  1  2  3  4  5  6
#  7  8  9 10 11 12
# 13 14 15 16 17 18
# 19 20 21 22 23 24
# 25 26 27 28 29 30
# 31 32 33 34 35 36

In [163]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[2:4, 6] # linhas 2, 3 e 4 na coluna 6

3-element Array{Int64,1}:
 12
 18
 24

In [164]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[2, 3:5] # colunas 3, 4 e 5 na linha 2

3-element Array{Int64,1}:
  9
 10
 11

#### Retornando as instâncias em um intervalo personalizado com o valor do *step* personalizado

In [ ]:
# matriz
#  1  2  3  4  5  6
#  7  8  9 10 11 12
# 13 14 15 16 17 18
# 19 20 21 22 23 24
# 25 26 27 28 29 30
# 31 32 33 34 35 36

In [165]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[2:2:6, 6] # linhas 2, 4 e 6 na coluna 6 (step = 2)

3-element Array{Int64,1}:
 12
 24
 36

In [166]:
matrix = [(i-1)*6+j for i = 1:6, j = 1:6]
matrix[2, 1:2:5] # colunas 1, 3 e 5 na linha 2 (step = 2)

3-element Array{Int64,1}:
  7
  9
 11

## Range

Uma estrutura muito útil presente no Julia, como vimos anteriormente, é o range. Ele é um objeto iterável e possui o funcionamento semelhante ao do Python. Contudo, a sua sintaxe é mais simples. A grande vantagem de utilizar um iterador é a desnecessidade de alocação em memória de um grande volume de dados.

Abaixo temos dois exemplos usando o laço `for` com um `range` e um `array`. É possível observar o uso do **operador três pontos** (`...`). Este, nos exemplos abaixo, transforma um range em um array para que possamos ver a diferença entre os dois casos.

In [167]:
@time for i in 1:20000
    nothing
end

  0.000000 seconds


In [168]:
@time for i in [1:20000...]
    nothing
end

  0.006801 seconds (117.97 k allocations: 3.105 MiB)


In [169]:
a = 1:2
typeof(a)

UnitRange{Int64}

In [170]:
a = [1:2...]
typeof(a)

Array{Int64,1}

## Multiple dispatch

É uma característica onde uma função ou método pode ser executado dinamicamente baseado no tipo de um ou mais argumentos

In [171]:
ex_md(x::String, y::String) = println("x e y são strings")

ex_md (generic function with 5 methods)

In [172]:
ex_md(x::Int, y::Int) = println("x e y são inteiros")

ex_md (generic function with 5 methods)

In [173]:
ex_md(x::Int, y::String) = println("x é inteiro e y é string")

ex_md (generic function with 5 methods)

In [174]:
ex_md("oi","oi")

x e y são strings


In [175]:
ex_md(3, 4)

x e y são inteiros


In [176]:
ex_md(3, "oi")

x é inteiro e y é string


## Funções especializadas

Um dos motivos atrelados a proporcionalidade de performance do Julia com o C é a compilação Just In Time, junto a criação de funções especializadas.

Um bom exemplo para mostrar essas funções especializadas são as operações aritméticas. Seu comportamento irá depender do tipo dos dados dos seus operandos que será determinado durante o tempo de execução.

In [177]:
function f(a, b)
    return 2a + b
end

f (generic function with 1 method)

In [178]:
@code_native f(2.0, 3.0)

	.text
; ┌ @ In[177]:2 within `f'
; │┌ @ promotion.jl:312 within `*' @ float.jl:405
	vaddsd	%xmm0, %xmm0, %xmm0
; │└
; │┌ @ float.jl:401 within `+'
	vaddsd	%xmm1, %xmm0, %xmm0
; │└
	retq
	nopl	(%rax)
; └


In [179]:
@code_native f(2, 3)

	.text
; ┌ @ In[177]:2 within `f'
; │┌ @ int.jl:86 within `+'
	leaq	(%rsi,%rdi,2), %rax
; │└
	retq
	nopw	%cs:(%rax,%rax)
	nop
; └


## Metaprogramação

Com Julia, é possível referir-se ao próprio código como objeto da linguagem. Assim, um programa pode ser capaz de alterar e gerar o próprio código.

In [181]:
macro sayhello()
           return :( println("Hello, world!") )
       end
macro sayhello(name)
           return :( println("Hello, ", $name) )
       end

@sayhello (macro with 2 methods)

In [182]:
@sayhello

Hello, world!


In [183]:
@sayhello "Julia"

Hello, Julia


In [184]:
@sayhello("Julia")

Hello, Julia


Macros podem tornar a realização de tarefas usuais mais prática. Por exemplo, a macro `@macroexpand` permite ver o que ocorre dentro de uma macro. No código abaixo, ela exibe o funcionamento da macro `@elapsed`, que por sua vez retorna a marcação do tempo que a função peakflops() leva para ser executada.

In [188]:
Base.remove_linenums!(@macroexpand @elapsed peakflops())

quote
    while false
    end
    local var"#49#t0" = Base.time_ns()
    peakflops()
    (Base.time_ns() - var"#49#t0") / 1.0e9
end

In [187]:
@elapsed peakflops() #em segundos

0.70358026

In [186]:
peakflops()

3.1652327980749924e10

O uso de macros pode tornar o código muito mais legível:

In [189]:
ccall(:strlen, Cint, (Cstring,), "Maria")

5

In [190]:
@ccall strlen("Maria"::Cstring)::Cint

5

### Macros de Performance

**_@inbounds_** permite a eliminação de checagem de borda em Arrays nas expressões passadas.

**_@fastmath_** permite otimizações em operações de ponto flutuante que retorna um resutado para números reais, mas pode mudar resultados que dependem de precisão.

**_@simd_** é uma macro que permite que o compilador utilize vetorização SIMD, prometendo que os valores no loop são independentes e podem ser reordenados. É possível que o compilador faça essa otimização em muitos casos. A macro é indicada para autorizar quando a alteração da ordem seria ilegal, como em operações de ponto-flutuante que possam gerar valores indesejados.

## Pacotes

Julia dispõe de um sistema de gerenciamento de pacotes oficial, o Pkg. Ele é responsável por adicionar, atualizar e remover pacotes do seu ambiente. Todo pacote possui um nome, um identificador único e um número de versão. É um sistema robusto que permite cada pacote compile sempre as dependências corretas para aquela versão.

In [ ]:
using Pkg; Pkg.add("BenchmarkTools")

### Ecossistema:

<tr valign="center" width="100%" style="border: none;">
 <td valign="center" style="border: none;" width="100px">
    <img align="left" src="https://i.imgur.com/5wiVwj6.png" width="130px"/> 
  </td>
  <td align="left" valign= "center" style="border: none;" width="80%">
      <body > JuMP: Uma linguagem de modelagem embutida em <br> Julia para resolução de problemas de otimização. </body>
    <td>
</tr>
<tr valign="center" width="100%" style="border: none;">
 <td valign="center" style="border: none;" width="100px">
    <img align="left" src="https://i.imgur.com/fzX8niP.png" width="130px"/> 
  </td>
  <td align="left" valign= "center" style="border: none;" width="80%">
      <body > Um pacote para resolver equações diferenciais numericamente. </body>
    <td>
</tr>
</tr>
<tr valign="center" width="100%" style="border: none;">
 <td valign="center" style="border: none;" width="100px">
    <img align="left" src="https://i.imgur.com/abCGYhv.png" width="130px"/> 
  </td>
  <td align="left" valign= "center" style="border: none;" width="80%">
      <body > Uma biblioteca para machine learning altamente <br> integrada com vários pacotes da linguagem. </body>
    <td>
</tr>
<tr valign="center" width="100%" style="border: none;">
 <td valign="center" style="border: none;" width="100px">
    <img align="left" src="https://i.imgur.com/nXBr4PZ.png" width="130px"/> 
  </td>
  <td align="left" valign= "center" style="border: none;" width="80%">
      <body > Um framework de seleção, tuning, avaliação, <br> 
          composição e comparação de modelos de machine learning. </body>
    <td>
</tr>

### Synthetic Datasets

Um pacote desenvolvido no ATIS-Labs para a geração de Datasets sintéticos.

<tr valign="center" width="50%" style="border: none;">
 <td valign="center" style="border: none;" width="50%">
    <img align="left" src="https://i.imgur.com/MWgSJsa.png" width="600px"/> 
  </td>
  <td align="left" valign= "center" style="border: none;" width="50%">
      <img align="left" src="https://i.imgur.com/cTQmC8c.gif" width="600px"/>
    <td>
</tr>

link: http://synthetic.atislabs.com.br/