In [1]:
using Pkg
Pkg.activate(".")
using CSV, DataFrames, StaticArrays

path = "../data/"
movies = CSV.File(path * "movies.csv") |> DataFrame;
movies = movies[1:10, :]

 Activating new environment at `~/Project.toml`


LoadError: ArgumentError: Package StaticArrays not found in current path:
- Run `import Pkg; Pkg.add("StaticArrays")` to install the StaticArrays package.


## Declaração das Variáveis
Julia é uma linguagem que oferece o melhor dos dois mundos no que tange a tipagem dos dados. Além de oferecer a versatilidade de um sistema de tipagem dinâmica, também
oferece a possibilidade de declaração de tipos, trazendo para si o ganho de performance oferecido por este sistema.

In [1]:
x = 20
typeof(x)

Int64

In [3]:
x = 1.5
typeof(x)

Float64

In [4]:
x = "20"
typeof(x)

String

Nestes casos, podem ser atribuídos diferentes tipos de valores a variável `x`, por conta da tipagem dinâmica. Para a definição dos tipos em Julia, é necessário o uso do operador `::` que define um tipo estático à variável. Porém, atualmente, não é possível a definição de tipos no escopo global.

In [5]:
x::Int64 = 1

LoadError: syntax: type declarations on global variables are not yet supported

### Situações onde a definição de tipos é possível:

In [0]:
function foo()
   x::Int64 = 100
   x
end

In [0]:
function foo()::Int64
   x::Int64 = 100
   x
end

In [0]:
function foo(x::Int64)
   x
end

In [0]:
struct teste
    number::Int64
end

### Funções
Nos exemplos acima, mostramos a declaração de tipos em uma função. Essa função, assim como as funções no geral em Julia e em outras linguagens, são operações agrupadas em um
escopo que serão executadas toda vez que a função for chamada. Desta forma, podemos evitar repetição de código, deixando-o mais limpo e legível.

Para definir uma função, começamos com a *keyword* `function` seguida pelo nome da função e, entre parênteses os parâmetros. Seu corpo, assim como as estruturas condicionais ou de repetição (faladas mais adiante), possuem o corpo identado com um *tab*, o que não é necessário, e terminam com a *keyword* `end`.

In [3]:
function example()
    corpo_identado
end

example (generic function with 1 method)

#### Exemplo

Caso queiramos implementar uma função que recebe dois valores e nos retorna a soma desses valores, fazemos

In [5]:
function sum(a, b)
    return a + b
end

sum (generic function with 1 method)

A função acima nos retorna a soma de dois números. Porém, a função não define o tipo dos parâmetros e do retorno da função. Assim, podemos passar valores como 9.2 ou até mesmo
algum valor em `String` para a função, o que resultaria em um erro. Se quisermos definir o tipo dos parâmetros e do retorno da função, vamos utilizar o conceito visto anteriormente
sobre tipagem. Faremos

In [0]:
function sum(a::Int8, b::Int8)::Int8
    return a + b
end

Desta forma fazemos com que a função obrigue os parâmetros recebidos a serem do tipo `Int8` e o retorno a ser, também, um Int8.

Outra maneira de se criar uma função é a partir desta forma mais curta

In [13]:
sum(a::Int8, b::Int8)::Int8 = a + b

sum (generic function with 2 methods)

Além disso, a linguagem também permite a criação de funções anônimas.

In [15]:
(x) -> x + 2

#3 (generic function with 1 method)

## Estruturas condicionais

Quando queremos dar um rumo à tarefa de acordo com um condição, utilizamos as chamadas **estruturas condicionais**. Estas são estruturas que utilizam condições para a realização de alguma tarefa. Assim, caso tenhamos dois ou mais caminhos a serem seguidos baseados em alguma condição, podemos usar essas estruturas para separar e definir cada um desses possíveis caminhos a serem seguidos de acordo com o resultado desta condição, que posse ser verdadeira, com o valor lógico `true`, ou falsa, com o valor lógico `false`.

In [8]:
x = 3
y = 5

if x > y
    print("X é maior.")
end

Acima temos uma estrutura condicional simples, onde apenas o caso verdadeiro é executado. No entanto, caso queiramos que alguma tarefa seja executada para o caso
de essa expressão retornar o valor `false`, utilizamos a *keyword* `else`, da seguinte forma:

In [9]:
x = 3
y = 5

if x > y
    print("X é maior")
else
    print("X é menor.")
end

X é menor.

Desta forma, caso o valor contido em X NÃO seja maior do que o valor contido em Y, o programa irá mostrar uma outra mensagem, informando que X é menor. 
Porém, existe uma outra condição para o caso de a primeira ser falsa: o caso em que x é **igual** a y. Se deixarmos o programa do jeito que está acima e
essa condição for satisfeita, teremos uma saída errada. Podemos, para resolver esse problema, adicionar um outro `if` para que ele teste se o valor contido
em x é igual ao valor contido em Y. Entretanto, usar apenas `if`s faz com que nosso programa perca desempenho, visto que ele terá de testar **todas** as condições
mesmo que a primeira já tenha dado o valor `true`.
Assim, conheceremos uma nova keyword: a `elseif`.

In [10]:
x = 3
y = 5

if x > y
    print("X é maior do que Y")
elseif x == y
    print("X é igual a Y")
else
    print("X é menor do que Y")
end

X é menor do que Y

O `elseif` faz a mesma coisa que um `if` dentro um `else`. Ou seja, caso a expressão do `if` retorne um valor `false`, o `elseif` é acionado e faz uma outra condição.
No exemplo acima, a condição é verificar se o valor de X é igual ao valor de Y.

### Operador ternário

O operador ternário funciona como um if-else mais simplificado. Para fazê-lo, basta digitar `a ? B : c`, onde `a` é a condição, `b` é a operação caso a condição seja 
verdadeira e `c` é a operação caso a condição seja falsa.
Por exemplo, suponhamos que queremos *printar* uma mensagem na tela dependendo do valor de um número, armazenado em `x`: caso este valor seja maior do que 3.14, *printamos*
"Maior que PI" e, caso contrário, "Menor ou igual a PI".

In [11]:
x = 3.18
print(x > 3.14 ? "Maior que PI" : "Menor ou igual a PI")

Maior que PI

Desta forma, temos um print mais simplificado. Se usássemos, ao invés disso, o if-else convencional, teríamos 5 linhas de código.

### Vetores

Vetores (ou *arrays* unidimensionais) são estruturas que armazenam dados de um mesmo tipo. Isto é, caso queiramos armazenar o nome de todos os alunos de uma sala, por exemplo, podemos armazená-los em um vetor. Em Julia, vetores são inicializados utilizando a *keyword* `Array` e, entre chaves (`{}`), dizemos o tipo do vetor e sua dimensão, seguido de `(undef, length)`, onde `undef` diz ao compilador que estamos apenas alocando o espaço dos elementos do *array*, que é indefinido; e `length` o diz o tamanho de cada uma das dimensões do array.

In [2]:
array = Array{Int, 1}(undef, 2)

2-element Array{Int64,1}:
 139828070609424
 139828429591248

No exemplo acima, fazemos a declaração de um array de números inteiros, representados por `Int` de 1 dimensão e dizemos que teremos um tamanho igual a 2. Desta forma, temos um array unidimensional com dois elementos.

#### Inicialização com `zeros()`

Além de inicializar o vetor da forma que vimos acima, a linguagem Julia nos permite criar arrays com todos os elementos zerados utilizando a função `zeros()`, que pode receber parâmetros indicando o tipo e a dimensão do nosso array. Caso o tipo não seja definido, como vemos no primeiro exemplo abaixo, o array é criado com o tipo `Float64`. Já no exemplo mais abaixo, temos a definição do tipo do array para `Int`.

In [1]:
zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [2]:
zeros(Int, 2)

2-element Array{Int64,1}:
 0
 0

### Matrizes
As matrizes são formalmente definidas como uma dupla sequencia de valores distribuídos entre linhas e colunas e são uma das estruturas mais utilizadas para o agrupamento de valores com uma mesma finalidade.

As formas de inicialização desta estrutura são simples, como podemos ver abaixo:

In [14]:
matriz = Array{Int, 2}(undef, (2, 2))

2×2 Array{Int64,2}:
 140173946765680  140174926697168
 140174926713184  140174468641712

In [15]:
matriz = zeros((2, 2))

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [16]:
matriz = zeros(Int, (2, 2))

2×2 Array{Int64,2}:
 0  0
 0  0

### StaticArray

Um aspecto importante que deve ser observado e levado em consideração na construção de códigos quando um dos objetivos é alto desempenho é a preocupação com a alocação de memória.

No caso do Julia, sempre quando efetuamos a alocação de memoria usando estruturas dinâmicas, estruturas nas quais podem ser alocados diferentes tipos de dados, criamos a necessidade de um lugar para o armazenamento que disponibilize um redimensionamento do espaço. Logo, o alocamento destas estruturas acabam sendo destinado à HEAP e não à pilha, e em diversas situações isto pode ocasionar uma perda de performance no procedimento que normalmente já é o mais custoso nas aplicações.
Mas para a solução deste problema, temos uma Library com estruturas que inibem esse problema, com a criação de vetores e matrizes estáticas.

In [41]:
SVector{3,Float64}(zeros(3))

3-element SArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 0.0
 0.0
 0.0

In [40]:
SA[1, 2, 3]

3-element SArray{Tuple{3},Int64,1,3} with indices SOneTo(3):
 1
 2
 3

## Estruturas de repetição

Os laços de repetição são estruturas que têm como objetivo a execução repetida de uma determinada tarefa ao decorrer do código. Por exemplo, caso queiramos percorrer um vetor, podemos utilizar uma estrutura de repetição para iterar sobre os elementos armazenados na estrutura. O uso dessas estruturas de repetição facilitam nosso trabalho na manipulação de arrays.
Em Julia, estas estruturas têm como base alguma expressão condicional ou algum elemento iterável que dita até quando a determinada tarefa irá ser executada.

### Exemplo
Temos uma lista de filmes armazenadas em um vetor e queremos exibir o nome desses vetores. Cada um dos elementos do vetor representa um filme, que pode ser entendido, também, como um vetor com as informações deste filme, como seu nome, ano de lançamento etc. Assim, se quisermos acessar alguma dessas informações, o fazemos da mesma forma que acessamos a um elemento dentro de um vetor: usando colchetes (`[]`).

In [23]:
for i = 1:length(elementos)
    println(movies[i, 2])
end

Toy Story (1995)
Jumanji (1995)
Grumpier Old Men (1995)
Waiting to Exhale (1995)
Father of the Bride Part II (1995)
Heat (1995)
Sabrina (1995)
Tom and Huck (1995)
Sudden Death (1995)
GoldenEye (1995)


No exemplo acima, fazemos uma estrutura de repetição usando um **for loop** que itera sobre o array `elementos`. Essa iteração acontece de maneira simples: é criado uma variável que recebe um intervalo e, enquanto esse intervalo ainda não alcançar seu máximo, as tarefas dentro do escopo da estrutura são executadas. Nesse caso, nosso intervalo vai de 1 (quando fazemos `i = 1`) até o último elemento do nosso array, representado por `length(elementos)`. Dentro do escopo da estrutura, temos um `print` com `movies[i, 2]`. Esse `movies` faz referência ao atributo que criamos lá no início do notebook, com os filmes importados do dataset. Assim, a cada iteração, temos um novo valor para a variável `i`, que nos servirá de iterador para o nosso array.
Porém, ao invés disso, podemos, também, fazer um iterador já com o nome dos filmes. Nesse caso, nosso "intervalo" se baseia em cada um dos elementos contidos na nossa expressão. Por exemplo: abaixo, temos `elemento = movies[:, 2]`. Em outras palavras, essa expressão nos diz que a variável `elemento` vai receber **cada** um dos elementos contidos no array `movies[:, 2]`. 

#### Caractere ':'
Quando lidamos com array, podemos usar o caractere `:` para dizer "todo o intervalo". Então, caso tenhamos um array de duas dimensões e queremos os elementos de **todas** as linhas, mas apenas da terceira coluna, por exemplo, podemos fazer `array[:, 3]`.

In [24]:
for elemento = movies[:, 2]
    println(elemento)
end

Toy Story (1995)
Jumanji (1995)
Grumpier Old Men (1995)
Waiting to Exhale (1995)
Father of the Bride Part II (1995)
Heat (1995)
Sabrina (1995)
Tom and Huck (1995)
Sudden Death (1995)
GoldenEye (1995)


As estruturas acima percorrem os elementos do objeto posto após o símbolo de atribuição e, a cada iteração, o elemento atual é atribuído à variável contida antes do operador '=',
facilitando a execução de uma determinada tarefa sobre um conjunto de elementos alvo.

In [0]:
for elemento in elementos end

for i in 1:length(elementos) end


Já nesses casos, embora a mudança na sintaxe, temos o mesmo funcionamento. Mas, por questões de coerência na escrita, 
é aconselhável o uso destas estruturas para percorrer objetos iteraveis e o uso da estrutura anterior para percorrer 'ranges'.

### While loop
Aqui entramos nas estruturas que funcionam a partir de uma expressão condicional, onde a tarefa permanece sendo realizada enquanto a condição é satisfeita.

#### Exemplo:
Caso queiramos realizar uma tarefa somente sobre os primeiros elementos de um conjunto.
Neste caso queremos *imprimir* (tarefa) os elementos que tem o seu identificador menor que 5. Tal tarefa pode ser desempenhada desta forma:

In [5]:
i = 1
while movies[i, 1] < 5
    println("Id: ", movies[i, 1], "|", "Nome: ", movies[i, 2])
    i+=1
end

Id: 1|Nome: Toy Story (1995)
Id: 2|Nome: Jumanji (1995)
Id: 3|Nome: Grumpier Old Men (1995)
Id: 4|Nome: Waiting to Exhale (1995)
